inherit_mode:
  merge:
    - Exclude

require: rubocop-rails

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Bundler/OrderedGems:
  Enabled: false
